//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RambotRepository
{

    public partial class DiscordUser
    {
        public string did { get; set; }
        public System.Guid Rid { get; set; }
    
        public virtual RamUser RamUser { get; set; }
    }
}
