//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RambotRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RAMBOTEntities : DbContext
    {
        public RAMBOTEntities()
            : base("name=RAMBOTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClipUse> ClipUses { get; set; }
        public virtual DbSet<CommandUse> CommandUses { get; set; }
        public virtual DbSet<DiscordRam> DiscordRams { get; set; }
        public virtual DbSet<DiscordUser> DiscordUsers { get; set; }
        public virtual DbSet<LoginClip> LoginClips { get; set; }
        public virtual DbSet<RamActivityLog> RamActivityLogs { get; set; }
        public virtual DbSet<RamLink> RamLinks { get; set; }
        public virtual DbSet<RamUser> RamUsers { get; set; }
        public virtual DbSet<TeamSpeakRam> TeamSpeakRams { get; set; }
        public virtual DbSet<TeamSpeakUser> TeamSpeakUsers { get; set; }
        public virtual DbSet<TeamSpeakLocalUser> TeamSpeakLocalUsers { get; set; }
        public virtual DbSet<RamErrorLog> RamErrorLogs { get; set; }
    }
}
