//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RambotRepository
{

    public partial class RamErrorLog
    {
        public System.DateTime time { get; set; }
        public string stack { get; set; }
        public string message { get; set; }
        public System.Guid by { get; set; }
        public string line { get; set; }
        public string ramName { get; set; }
        public string serverId { get; set; }
    }
}
